/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoHonoTodoRouteImport } from './routes/demo/hono-todo'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as CategoriesCategorySlugRouteImport } from './routes/categories/$categorySlug'
import { Route as BuyerRfqsRouteImport } from './routes/buyer/rfqs'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as BuyerRfqsRfqIdRouteImport } from './routes/buyer/rfqs/$rfqId'
import { Route as ApiRfqSubmitRouteImport } from './routes/api/rfq/submit'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiRfqSupplierSupplierIdRouteImport } from './routes/api/rfq/supplier/$supplierId'
import { Route as ApiRfqBuyerBuyerIdRouteImport } from './routes/api/rfq/buyer/$buyerId'
import { Route as ApiRfqRfqIdQuotesRouteImport } from './routes/api/rfq/$rfqId.quotes'
import { Route as ApiRfqRfqIdQuoteRouteImport } from './routes/api/rfq/$rfqId.quote'
import { Route as ApiRfqQuoteQuoteIdRejectRouteImport } from './routes/api/rfq/quote/$quoteId.reject'
import { Route as ApiRfqQuoteQuoteIdCounterRouteImport } from './routes/api/rfq/quote/$quoteId.counter'
import { Route as ApiRfqQuoteQuoteIdAcceptRouteImport } from './routes/api/rfq/quote/$quoteId.accept'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHonoTodoRoute = DemoHonoTodoRouteImport.update({
  id: '/demo/hono-todo',
  path: '/demo/hono-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategorySlugRoute = CategoriesCategorySlugRouteImport.update({
  id: '/categories/$categorySlug',
  path: '/categories/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRfqsRoute = BuyerRfqsRouteImport.update({
  id: '/buyer/rfqs',
  path: '/buyer/rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRfqsRfqIdRoute = BuyerRfqsRfqIdRouteImport.update({
  id: '/$rfqId',
  path: '/$rfqId',
  getParentRoute: () => BuyerRfqsRoute,
} as any)
const ApiRfqSubmitRoute = ApiRfqSubmitRouteImport.update({
  id: '/api/rfq/submit',
  path: '/api/rfq/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRfqSupplierSupplierIdRoute =
  ApiRfqSupplierSupplierIdRouteImport.update({
    id: '/api/rfq/supplier/$supplierId',
    path: '/api/rfq/supplier/$supplierId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRfqBuyerBuyerIdRoute = ApiRfqBuyerBuyerIdRouteImport.update({
  id: '/api/rfq/buyer/$buyerId',
  path: '/api/rfq/buyer/$buyerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRfqRfqIdQuotesRoute = ApiRfqRfqIdQuotesRouteImport.update({
  id: '/api/rfq/$rfqId/quotes',
  path: '/api/rfq/$rfqId/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRfqRfqIdQuoteRoute = ApiRfqRfqIdQuoteRouteImport.update({
  id: '/api/rfq/$rfqId/quote',
  path: '/api/rfq/$rfqId/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRfqQuoteQuoteIdRejectRoute =
  ApiRfqQuoteQuoteIdRejectRouteImport.update({
    id: '/api/rfq/quote/$quoteId/reject',
    path: '/api/rfq/quote/$quoteId/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRfqQuoteQuoteIdCounterRoute =
  ApiRfqQuoteQuoteIdCounterRouteImport.update({
    id: '/api/rfq/quote/$quoteId/counter',
    path: '/api/rfq/quote/$quoteId/counter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRfqQuoteQuoteIdAcceptRoute =
  ApiRfqQuoteQuoteIdAcceptRouteImport.update({
    id: '/api/rfq/quote/$quoteId/accept',
    path: '/api/rfq/quote/$quoteId/accept',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/buyer/rfqs': typeof BuyerRfqsRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/hono-todo': typeof DemoHonoTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rfq/submit': typeof ApiRfqSubmitRoute
  '/buyer/rfqs/$rfqId': typeof BuyerRfqsRfqIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/rfq/$rfqId/quote': typeof ApiRfqRfqIdQuoteRoute
  '/api/rfq/$rfqId/quotes': typeof ApiRfqRfqIdQuotesRoute
  '/api/rfq/buyer/$buyerId': typeof ApiRfqBuyerBuyerIdRoute
  '/api/rfq/supplier/$supplierId': typeof ApiRfqSupplierSupplierIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/rfq/quote/$quoteId/accept': typeof ApiRfqQuoteQuoteIdAcceptRoute
  '/api/rfq/quote/$quoteId/counter': typeof ApiRfqQuoteQuoteIdCounterRoute
  '/api/rfq/quote/$quoteId/reject': typeof ApiRfqQuoteQuoteIdRejectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/buyer/rfqs': typeof BuyerRfqsRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/hono-todo': typeof DemoHonoTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rfq/submit': typeof ApiRfqSubmitRoute
  '/buyer/rfqs/$rfqId': typeof BuyerRfqsRfqIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/rfq/$rfqId/quote': typeof ApiRfqRfqIdQuoteRoute
  '/api/rfq/$rfqId/quotes': typeof ApiRfqRfqIdQuotesRoute
  '/api/rfq/buyer/$buyerId': typeof ApiRfqBuyerBuyerIdRoute
  '/api/rfq/supplier/$supplierId': typeof ApiRfqSupplierSupplierIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/api/rfq/quote/$quoteId/accept': typeof ApiRfqQuoteQuoteIdAcceptRoute
  '/api/rfq/quote/$quoteId/counter': typeof ApiRfqQuoteQuoteIdCounterRoute
  '/api/rfq/quote/$quoteId/reject': typeof ApiRfqQuoteQuoteIdRejectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/buyer/rfqs': typeof BuyerRfqsRouteWithChildren
  '/categories/$categorySlug': typeof CategoriesCategorySlugRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/hono-todo': typeof DemoHonoTodoRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rfq/submit': typeof ApiRfqSubmitRoute
  '/buyer/rfqs/$rfqId': typeof BuyerRfqsRfqIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/rfq/$rfqId/quote': typeof ApiRfqRfqIdQuoteRoute
  '/api/rfq/$rfqId/quotes': typeof ApiRfqRfqIdQuotesRoute
  '/api/rfq/buyer/$buyerId': typeof ApiRfqBuyerBuyerIdRoute
  '/api/rfq/supplier/$supplierId': typeof ApiRfqSupplierSupplierIdRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/api/rfq/quote/$quoteId/accept': typeof ApiRfqQuoteQuoteIdAcceptRoute
  '/api/rfq/quote/$quoteId/counter': typeof ApiRfqQuoteQuoteIdCounterRoute
  '/api/rfq/quote/$quoteId/reject': typeof ApiRfqQuoteQuoteIdRejectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/wishlist'
    | '/api/$'
    | '/auth/set-password'
    | '/buyer/rfqs'
    | '/categories/$categorySlug'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/hono-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/products/$productSlug'
    | '/api/auth/$'
    | '/api/rfq/submit'
    | '/buyer/rfqs/$rfqId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/rfq/$rfqId/quote'
    | '/api/rfq/$rfqId/quotes'
    | '/api/rfq/buyer/$buyerId'
    | '/api/rfq/supplier/$supplierId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/rfq/quote/$quoteId/accept'
    | '/api/rfq/quote/$quoteId/counter'
    | '/api/rfq/quote/$quoteId/reject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/wishlist'
    | '/api/$'
    | '/auth/set-password'
    | '/buyer/rfqs'
    | '/categories/$categorySlug'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/hono-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/products/$productSlug'
    | '/api/auth/$'
    | '/api/rfq/submit'
    | '/buyer/rfqs/$rfqId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/rfq/$rfqId/quote'
    | '/api/rfq/$rfqId/quotes'
    | '/api/rfq/buyer/$buyerId'
    | '/api/rfq/supplier/$supplierId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
    | '/api/rfq/quote/$quoteId/accept'
    | '/api/rfq/quote/$quoteId/counter'
    | '/api/rfq/quote/$quoteId/reject'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/orders'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/wishlist'
    | '/api/$'
    | '/auth/set-password'
    | '/buyer/rfqs'
    | '/categories/$categorySlug'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/hono-todo'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/products/$productSlug'
    | '/api/auth/$'
    | '/api/rfq/submit'
    | '/buyer/rfqs/$rfqId'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/rfq/$rfqId/quote'
    | '/api/rfq/$rfqId/quotes'
    | '/api/rfq/buyer/$buyerId'
    | '/api/rfq/supplier/$supplierId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
    | '/api/rfq/quote/$quoteId/accept'
    | '/api/rfq/quote/$quoteId/counter'
    | '/api/rfq/quote/$quoteId/reject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  BuyerRfqsRoute: typeof BuyerRfqsRouteWithChildren
  CategoriesCategorySlugRoute: typeof CategoriesCategorySlugRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoHonoTodoRoute: typeof DemoHonoTodoRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRfqSubmitRoute: typeof ApiRfqSubmitRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiRfqRfqIdQuoteRoute: typeof ApiRfqRfqIdQuoteRoute
  ApiRfqRfqIdQuotesRoute: typeof ApiRfqRfqIdQuotesRoute
  ApiRfqBuyerBuyerIdRoute: typeof ApiRfqBuyerBuyerIdRoute
  ApiRfqSupplierSupplierIdRoute: typeof ApiRfqSupplierSupplierIdRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  ApiRfqQuoteQuoteIdAcceptRoute: typeof ApiRfqQuoteQuoteIdAcceptRoute
  ApiRfqQuoteQuoteIdCounterRoute: typeof ApiRfqQuoteQuoteIdCounterRoute
  ApiRfqQuoteQuoteIdRejectRoute: typeof ApiRfqQuoteQuoteIdRejectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/hono-todo': {
      id: '/demo/hono-todo'
      path: '/demo/hono-todo'
      fullPath: '/demo/hono-todo'
      preLoaderRoute: typeof DemoHonoTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categorySlug': {
      id: '/categories/$categorySlug'
      path: '/categories/$categorySlug'
      fullPath: '/categories/$categorySlug'
      preLoaderRoute: typeof CategoriesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/rfqs': {
      id: '/buyer/rfqs'
      path: '/buyer/rfqs'
      fullPath: '/buyer/rfqs'
      preLoaderRoute: typeof BuyerRfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/rfqs/$rfqId': {
      id: '/buyer/rfqs/$rfqId'
      path: '/$rfqId'
      fullPath: '/buyer/rfqs/$rfqId'
      preLoaderRoute: typeof BuyerRfqsRfqIdRouteImport
      parentRoute: typeof BuyerRfqsRoute
    }
    '/api/rfq/submit': {
      id: '/api/rfq/submit'
      path: '/api/rfq/submit'
      fullPath: '/api/rfq/submit'
      preLoaderRoute: typeof ApiRfqSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/supplier/$supplierId': {
      id: '/api/rfq/supplier/$supplierId'
      path: '/api/rfq/supplier/$supplierId'
      fullPath: '/api/rfq/supplier/$supplierId'
      preLoaderRoute: typeof ApiRfqSupplierSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/buyer/$buyerId': {
      id: '/api/rfq/buyer/$buyerId'
      path: '/api/rfq/buyer/$buyerId'
      fullPath: '/api/rfq/buyer/$buyerId'
      preLoaderRoute: typeof ApiRfqBuyerBuyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/$rfqId/quotes': {
      id: '/api/rfq/$rfqId/quotes'
      path: '/api/rfq/$rfqId/quotes'
      fullPath: '/api/rfq/$rfqId/quotes'
      preLoaderRoute: typeof ApiRfqRfqIdQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/$rfqId/quote': {
      id: '/api/rfq/$rfqId/quote'
      path: '/api/rfq/$rfqId/quote'
      fullPath: '/api/rfq/$rfqId/quote'
      preLoaderRoute: typeof ApiRfqRfqIdQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/quote/$quoteId/reject': {
      id: '/api/rfq/quote/$quoteId/reject'
      path: '/api/rfq/quote/$quoteId/reject'
      fullPath: '/api/rfq/quote/$quoteId/reject'
      preLoaderRoute: typeof ApiRfqQuoteQuoteIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/quote/$quoteId/counter': {
      id: '/api/rfq/quote/$quoteId/counter'
      path: '/api/rfq/quote/$quoteId/counter'
      fullPath: '/api/rfq/quote/$quoteId/counter'
      preLoaderRoute: typeof ApiRfqQuoteQuoteIdCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq/quote/$quoteId/accept': {
      id: '/api/rfq/quote/$quoteId/accept'
      path: '/api/rfq/quote/$quoteId/accept'
      fullPath: '/api/rfq/quote/$quoteId/accept'
      preLoaderRoute: typeof ApiRfqQuoteQuoteIdAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BuyerRfqsRouteChildren {
  BuyerRfqsRfqIdRoute: typeof BuyerRfqsRfqIdRoute
}

const BuyerRfqsRouteChildren: BuyerRfqsRouteChildren = {
  BuyerRfqsRfqIdRoute: BuyerRfqsRfqIdRoute,
}

const BuyerRfqsRouteWithChildren = BuyerRfqsRoute._addFileChildren(
  BuyerRfqsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  BuyerRfqsRoute: BuyerRfqsRouteWithChildren,
  CategoriesCategorySlugRoute: CategoriesCategorySlugRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoHonoTodoRoute: DemoHonoTodoRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRfqSubmitRoute: ApiRfqSubmitRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiRfqRfqIdQuoteRoute: ApiRfqRfqIdQuoteRoute,
  ApiRfqRfqIdQuotesRoute: ApiRfqRfqIdQuotesRoute,
  ApiRfqBuyerBuyerIdRoute: ApiRfqBuyerBuyerIdRoute,
  ApiRfqSupplierSupplierIdRoute: ApiRfqSupplierSupplierIdRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  ApiRfqQuoteQuoteIdAcceptRoute: ApiRfqQuoteQuoteIdAcceptRoute,
  ApiRfqQuoteQuoteIdCounterRoute: ApiRfqQuoteQuoteIdCounterRoute,
  ApiRfqQuoteQuoteIdRejectRoute: ApiRfqQuoteQuoteIdRejectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
